### ISSUE TITLE
[Elasticsearch] Adapt on datastream and ILM

### ISSUE THREAD

**Issue by paramite** [infrawatch/sg-core#48]
With ES v7.9 index naming is managed by ILM (index lifecycle management) in so-called data streams which from sg-core side means we need to prepare component templates and index templates both for events and logs.

The fact that we don't have it now means that indexes created by sg-core are named with ".ds" prefix and numeric suffix. This does not mean we are loosing data or sg-core would be not fuctional, but causes inconvenience when querying the data afterwards.
 
[1] https://www.elastic.co/blog/an-introduction-to-the-elastic-data-stream-naming-scheme

**Comment by paramite** [comment]
Useful info at https://opster.com/elasticsearch-glossary/elasticsearch-data-streams/

**Comment by leifmadsen** [comment]
Closing this as Won't Fix.
