### ISSUE TITLE
Suspect duplicate events would be created in HA mode

### ISSUE THREAD

**Issue by csibbitt** [infrawatch/sg-core#51]
The new ES client code uses a fresh uuid for every event: https://github.com/infrawatch/sg-core/blob/f5c2bb6641e9f2a2b032d85c29f4b3ff199ef7a5/plugins/application/elasticsearch/pkg/lib/client.go#L163

During HA testing of the old SG code, we implemented a content-based hash for the document ID instead, so that events received by multiple smart gateways in HA mode would not be duplicated in ES: https://github.com/infrawatch/smart-gateway/pull/88/files

The same logic is required here.

**Comment by leifmadsen** [comment]
https://issues.redhat.com/browse/STF-452

**Comment by csibbitt** [comment]
I was unable to reproduce this problem and suspect it only applies when using a dual-active HA mode, which is not something we ended up supporting. 
![image](https://user-images.githubusercontent.com/5091372/212971128-873adbc0-dabf-4745-ad64-6f489121f00d.png)
