### ISSUE TITLE
Differentiate metrics/events based on transport

### ISSUE THREAD

**Issue by pleimer** [infrawatch/sg-core#64]
If sg-core is configured to run with more than one transport, there is currently no way of differentiating from which transport each message comes. This means possible aliasing between metrics/events stored in any back-end if incoming messages from different locations happen to contain all of the same identifying information, a very likely scenario when using sg-core to consume information from multiple clouds.

There are a few approaches we can take to resolve this issue:

1. Add a configuration option to the handler plugins that allows for the manual addition of labels to metrics passing through that handler. This would allow us to specify a label containing the address in the config file. The drawback here is that we (or the SGO) must manually specify this new label

2. Have the socket plugin append bytes indicating the path of the socket to the message. In this scenario, the handlers must understand the protocol and extract the bytes before parsing the json. The handlers can add a label with the bytes. The drawback  is that a new protocol must exist between the transport and handlers, but this can be made the standard internally and all transports/handlers made to abide by it.

3. Create a standard for transport plugins to pass metadata information to handlers on startup. For example, the socket plugin could pass it's path configuration to the handlers so that the handlers can add it as a label to all incoming metrics and events.

#3 is probably my favourite option.

**Comment by leifmadsen** [comment]
Closing this out Won't Fix.
